

#if !defined( __COMMON_CTRL_TYPE_H__ )
#define __COMMON_CTRL_TYPE_H__

#include "../basexxx.h"

#define GUI_CTRL_TEMPLATE_NONE							-1
#define GUI_CTRL_TEMPLATE_STATIC_TEXT					0
#define GUI_CTRL_TEMPLATE_EDIT_BOX						1
#define GUI_CTRL_TEMPLATE_DROPDOWN_COMBO_BOX			2
#define GUI_CTRL_TEMPLATE_OPEN_FILE_EDIT_BOX			3
#define GUI_CTRL_TEMPLATE_FORMULATOR_EDIT_BOX			4
#define GUI_CTRL_TEMPLATE_COLOR_COMBO_BOX				5

#define GUI_CTRL_TEMPLATE_NAME_NONE						_T("none")
#define GUI_CTRL_TEMPLATE_NAME_STATIC_TEXT				_T("static")
#define GUI_CTRL_TEMPLATE_NAME_EDIT_BOX					_T("edit box")
#define GUI_CTRL_TEMPLATE_NAME_DROPDOWN_COMBO_BOX		_T("dropdown combo box")
#define GUI_CTRL_TEMPLATE_NAME_OPEN_FILE_EDIT_BOX		_T("open file edit box")
#define GUI_CTRL_TEMPLATE_NAME_FORMULATOR_EDIT_BOX		_T("formulator edit box")
#define GUI_CTRL_TEMPLATE_NAME_COLOR_COMBO_BOX			_T("color combo box")

#define GUI_CTRL_TEMPLATE_PARAM_NAME_PREDEFINED			_T("predefined")
#define GUI_CTRL_TEMPLATE_PARAM_NAME_ALLFILES			_T("all files")

#endif //__COMMON_CTRL_TYPE_H__
